"""Tests for dashboard_modules.bundle_builder.ensure_bundle_fresh.

These tests exercise the auto-rebuild guard that keeps the dashboard's
JS/CSS bundle in sync with its source files. They use a temp tree shaped
like dashboard_static/ (src/, css/, dist/) plus a stub package.json,
and stub `npm` with a tiny shell script so we never spawn real Node.
"""

import os
import stat
import textwrap
import time
from pathlib import Path

import pytest

from dashboard_modules.bundle_builder import ensure_bundle_fresh


def _make_static_tree(root: Path) -> tuple[Path, Path]:
    """Create a minimal dashboard_static/ + base_dir layout.

    Returns (static_dir, base_dir).
    """
    static = root / "dashboard_static"
    (static / "src").mkdir(parents=True)
    (static / "css").mkdir(parents=True)
    (static / "dist").mkdir(parents=True)

    # Existing source + already-built bundle.
    (static / "src" / "main.js").write_text("console.log('hi');\n")
    (static / "css" / "main.css").write_text("body { color: red; }\n")
    (static / "dist" / "bundle.min.js").write_text("// built\n")

    base = root
    (base / "package.json").write_text('{"name":"test","scripts":{"build":"echo built"}}\n')

    # Make the bundle 60s newer than sources so default state is "fresh".
    now = time.time()
    os.utime(static / "src" / "main.js", (now - 60, now - 60))
    os.utime(static / "css" / "main.css", (now - 60, now - 60))
    os.utime(static / "dist" / "bundle.min.js", (now, now))

    return static, base


def _install_fake_npm(bin_dir: Path, monkeypatch, behavior: str = "success",
                     touch_target: Path | None = None) -> Path:
    """Drop a fake `npm` shim on PATH.

    behavior:
      - "success": exits 0 and (if touch_target given) updates its mtime.
      - "fail": exits 1 with a stderr message.
      - "noop": exits 0 but does not touch the bundle (simulates a build that
                claims success but produced nothing).
    """
    bin_dir.mkdir(parents=True, exist_ok=True)
    shim = bin_dir / "npm"

    if behavior == "success":
        body = f'#!/bin/bash\ntouch "{touch_target}"\necho "built"\nexit 0\n'
    elif behavior == "fail":
        body = '#!/bin/bash\necho "build failed" 1>&2\nexit 1\n'
    elif behavior == "noop":
        body = '#!/bin/bash\necho "no-op"\nexit 0\n'
    else:
        raise ValueError(behavior)

    shim.write_text(body)
    shim.chmod(shim.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    monkeypatch.setenv("PATH", f"{bin_dir}:{os.environ.get('PATH', '')}")
    return shim


def test_fresh_bundle_no_rebuild(tmp_path, monkeypatch):
    static, base = _make_static_tree(tmp_path)
    monkeypatch.delenv("ATLASFORGE_SKIP_BUNDLE_BUILD", raising=False)

    # Even if npm is on PATH, a fresh bundle should not be rebuilt.
    _install_fake_npm(tmp_path / "bin", monkeypatch, behavior="fail")

    result = ensure_bundle_fresh(static, base)
    assert result["status"] == "fresh"
    assert result["src_mtime"] <= result["dist_mtime"]


def test_stale_bundle_triggers_rebuild(tmp_path, monkeypatch):
    static, base = _make_static_tree(tmp_path)
    monkeypatch.delenv("ATLASFORGE_SKIP_BUNDLE_BUILD", raising=False)

    # Make a source file newer than the bundle.
    future = time.time() + 10
    os.utime(static / "src" / "main.js", (future, future))

    bundle = static / "dist" / "bundle.min.js"
    _install_fake_npm(tmp_path / "bin", monkeypatch, behavior="success",
                      touch_target=bundle)

    pre_mtime = bundle.stat().st_mtime
    result = ensure_bundle_fresh(static, base)
    assert result["status"] == "rebuilt", result
    assert "src newer than dist" in result["reason"]
    # Bundle was retouched by the fake npm shim.
    assert bundle.stat().st_mtime > pre_mtime


def test_stale_css_triggers_rebuild(tmp_path, monkeypatch):
    """CSS source changes should also trigger a rebuild — bundle.min.css
    is regenerated by the same npm script."""
    static, base = _make_static_tree(tmp_path)
    monkeypatch.delenv("ATLASFORGE_SKIP_BUNDLE_BUILD", raising=False)

    future = time.time() + 10
    os.utime(static / "css" / "main.css", (future, future))

    bundle = static / "dist" / "bundle.min.js"
    _install_fake_npm(tmp_path / "bin", monkeypatch, behavior="success",
                      touch_target=bundle)

    result = ensure_bundle_fresh(static, base)
    assert result["status"] == "rebuilt", result


def test_missing_dist_triggers_rebuild(tmp_path, monkeypatch):
    static, base = _make_static_tree(tmp_path)
    monkeypatch.delenv("ATLASFORGE_SKIP_BUNDLE_BUILD", raising=False)

    bundle = static / "dist" / "bundle.min.js"
    bundle.unlink()

    _install_fake_npm(tmp_path / "bin", monkeypatch, behavior="success",
                      touch_target=bundle)

    result = ensure_bundle_fresh(static, base)
    assert result["status"] == "rebuilt"
    assert "missing" in result["reason"]


def test_skip_env_var_short_circuits(tmp_path, monkeypatch):
    static, base = _make_static_tree(tmp_path)

    # Make src newer so it would normally rebuild.
    future = time.time() + 10
    os.utime(static / "src" / "main.js", (future, future))

    monkeypatch.setenv("ATLASFORGE_SKIP_BUNDLE_BUILD", "1")
    # Install a npm that would FAIL — proves we never invoked it.
    _install_fake_npm(tmp_path / "bin", monkeypatch, behavior="fail")

    result = ensure_bundle_fresh(static, base)
    assert result["status"] == "skipped"
    assert "ATLASFORGE_SKIP_BUNDLE_BUILD" in result["reason"]


def test_no_npm_returns_no_npm_status(tmp_path, monkeypatch):
    static, base = _make_static_tree(tmp_path)
    monkeypatch.delenv("ATLASFORGE_SKIP_BUNDLE_BUILD", raising=False)

    future = time.time() + 10
    os.utime(static / "src" / "main.js", (future, future))

    # Empty PATH so no npm is reachable.
    monkeypatch.setenv("PATH", "/nonexistent")

    result = ensure_bundle_fresh(static, base)
    assert result["status"] == "no_npm"


def test_build_failure_is_reported_not_raised(tmp_path, monkeypatch):
    static, base = _make_static_tree(tmp_path)
    monkeypatch.delenv("ATLASFORGE_SKIP_BUNDLE_BUILD", raising=False)

    future = time.time() + 10
    os.utime(static / "src" / "main.js", (future, future))

    _install_fake_npm(tmp_path / "bin", monkeypatch, behavior="fail")

    # Must not raise even though the build exits non-zero.
    result = ensure_bundle_fresh(static, base)
    assert result["status"] == "build_failed"
    assert result["returncode"] == 1


def test_force_rebuild_bypasses_freshness_check(tmp_path, monkeypatch):
    static, base = _make_static_tree(tmp_path)
    monkeypatch.delenv("ATLASFORGE_SKIP_BUNDLE_BUILD", raising=False)

    bundle = static / "dist" / "bundle.min.js"
    _install_fake_npm(tmp_path / "bin", monkeypatch, behavior="success",
                      touch_target=bundle)

    # Bundle is fresh — without force, we'd skip. With force, we rebuild.
    result = ensure_bundle_fresh(static, base, force=True)
    assert result["status"] == "rebuilt"
    assert result["reason"] == "forced rebuild"


def test_no_package_json_falls_back_gracefully(tmp_path, monkeypatch):
    static, base = _make_static_tree(tmp_path)
    monkeypatch.delenv("ATLASFORGE_SKIP_BUNDLE_BUILD", raising=False)

    (base / "package.json").unlink()
    future = time.time() + 10
    os.utime(static / "src" / "main.js", (future, future))

    _install_fake_npm(tmp_path / "bin", monkeypatch, behavior="success")

    result = ensure_bundle_fresh(static, base)
    assert result["status"] == "no_package_json"
